version: '3'

services:
  home-assistant:
    image: homeassistant/home-assistant:2024.4.4
    container_name: home-assistant
    hostname: hahost
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /home/hass/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/vhci:/dev/vhci

