##
## door / doorphone
##

- alias: Door unlock
  trigger:
    - platform: state
      entity_id: lock.door_lock
      to: 'unlocked'
      for:
        minutes: 5
    - platform: state
      entity_id: lock.door_lock
      to: 'unlocked'
      for:
        minutes: 10
    - platform: state
      entity_id: lock.door_lock
      to: 'unlocked'
      for:
        minutes: 15
  condition:
    - condition: state
      entity_id: lock.door_lock
      state: 'unlocked'
  action:
    - service: tts.google_say
      entity_id: media_player.google_living
      data_template:
        message: "玄関の鍵が開いてます"
    - service: notify.mobile_app_iphone13_pro
      data:
        message: "鍵が開いてます"
        data:
          push:
            sound: "se_chakushin.wav"

- alias: Doorphone push
  trigger:
    - platform: state
      entity_id: sensor.doorphone_latest
  condition:
    - condition: state
      entity_id: person.me
      state: 'not_home'
  action:
    - service: notify.mobile_app_iphone13_pro
      data:
        message: "自宅に訪問者がいます"
        data:
          push:
            sound: "se_pinpon.wav"

