##
## tag
##

- id: ios_door_lock
  alias: "Door Lock/Unlock"
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: "ActionLock"
  condition:
    - condition: state
      entity_id: group.family_devices
      state: 'home'
  action:
    - service: "lock.{{ 'lock' if states('lock.door_lock') == 'unlocked' else 'unlock' }}"
      entity_id: lock.door_lock

- alias: "Door Lock Notify"
  trigger:
    - platform: state
      entity_id: lock.door_lock
      to:
  action:
    - delay:
        seconds: 1
    - service: notify.mobile_app_iphone13_pro
      data:
        message: update_complications

- id: ios_heat
  alias: "Action Heat"
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: "ActionHeat"
  action:
    - service: script.turn_on
      entity_id: script.heat_living
 
- id: ios_cool
  alias: "Action Cool"
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: "ActionCool"
  action:
    - service: script.turn_on
      entity_id: script.cool_living
 

