##
## tomorrow weather and informations
##

- alias: Tomorrow Info
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: time
      at: '01:00:00'
    - platform: time
      at: '02:00:00'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_living
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.google_living
      data_template:
        message: >
          {% if now().strftime('%H')|int==2 %}
            もう2時ですよ。
          {% endif %}
          {{ states('sensor.weather_forecast') }}
          {{ states('sensor.weather_forecast') }}
          {% if not is_state('sensor.trash_day', 'off') %}
            あと、
            {{ states('sensor.trash_day') }}
            {{ states('sensor.trash_day') }}
          {% endif %}

- alias: Night Jihou3
  trigger:
    - platform: time
      at: '03:00:00'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_living
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.google_living
      data_template:
        message: >
          {{ [
          "もう3時ですよ。",
          "3時になりました。",
          "3時になっちゃいました。",
          ] | random }}

- alias: Train Info
  trigger:
    - platform: time
      at: '07:45:00'
    - platform: time
      at: '07:50:00'
    - platform: time
      at: '09:05:00'
    - platform: time
      at: '09:15:00'
    - platform: time
      at: '09:25:00'
    - platform: time
      at: '09:45:00'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {{ not is_state('sensor.jr_info', '平常運転') }}
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_living
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.google_living
      data_template:
        message: >
          {{ states('sensor.jr_info') }}
          {{ states('sensor.jr_info') }}

