# binary_sensor

- platform: workday
  country: JP
  add_holidays:
    - '2019-08-13'
    - '2019-08-14'
    - '2019-08-15'
    - '2019-08-16'
    - '2019-12-30'
    - '2019-12-31'
    - '2020-01-02'
    - '2020-08-10'
    - '2020-08-11'
    - '2020-08-12'
    - '2020-08-13'
    - '2020-08-14'
    - '2020-12-28'
    - '2020-12-29'
    - '2020-12-30'
    - '2020-12-31'
    - '2021-01-04'
    - '2021-08-10'
    - '2021-08-11'
    - '2021-08-12'
    - '2021-08-13'
    - '2021-12-29'
    - '2021-12-30'
    - '2021-12-31'
    - '2022-01-03'
    - '2022-01-04'
    - '2022-01-31'
    - '2022-08-15'
    - '2022-08-16'
    - '2022-08-17'
    - '2022-08-18'
    - '2022-08-19'
    - '2022-12-29'
    - '2022-12-30'
    - '2023-01-02'
    - '2023-01-03'
    - '2023-01-04'
    - '2023-08-14'
    - '2023-08-15'
    - '2023-08-16'
    - '2023-08-17'
    - '2023-08-18'

- platform: template
  sensors:
    dishwasher:
      delay_off:
        minutes: 10
      value_template: >-
        {{ states('sensor.dishwasher_power')|float(0) > 3 }}
    drumwasher:
      delay_on:
        minutes: 5
      delay_off:
        minutes: 8
      value_template: >-
        {{ states('sensor.drumwasher_power')|float(0) > 50 }}

- platform: threshold
  name: cond_hot
  entity_id: sensor.outdoor_average
  upper: 24.5
  hysteresis: 0.5

- platform: threshold
  name: cond_cold
  entity_id: sensor.outdoor_average
  lower: 15.0
  hysteresis: 0.5

- platform: threshold
  name: cond_very_cold
  entity_id: sensor.outdoor_average
  lower: 12.0
  hysteresis: 0.5

