# circulator (fan)

- platform: mqtt
  name: "Living Circulator"
  state_topic:              "circulator/livingroom/power"
  command_topic:            "circulator/livingroom/power/set"
  percentage_state_topic:   "circulator/livingroom/fanmode"
  percentage_command_topic: "circulator/livingroom/fanmode/set"
  payload_on:  "on"
  payload_off: "off"
  speed_range_min: 1
  speed_range_max: 5
