# climate

- name: "Living Aircon"
  modes:
    - "off"
    - "auto"
    - "cool"
    - "heat"
    - "dry"
    - "fan"
  swing_modes:
    - "auto"
  fan_modes:
    - "auto"
  current_temperature_topic: "sensor/aircon/livingroom/temperature"
  current_humidity_topic:    "sensor/aircon/livingroom/humidity"
  mode_command_topic:        "aircon/livingroom/mode/set"
  mode_state_topic:          "aircon/livingroom/mode"
  temperature_command_topic: "aircon/livingroom/temperature/set"
  temperature_state_topic:   "aircon/livingroom/temperature"

- name: "Bedroom Aircon"
  modes:
    - "off"
    - "auto"
    - "cool"
    - "heat"
  swing_modes:
    - "auto"
  fan_modes:
    - "auto"
  current_temperature_topic: "sensor/aircon/bedroom/temperature"
  mode_command_topic:        "aircon/bedroom/mode/set"
  mode_state_topic:          "aircon/bedroom/mode"
  temperature_command_topic: "aircon/bedroom/temperature/set"
  temperature_state_topic:   "aircon/bedroom/temperature"
  payload_on: "on"
  payload_off: "off"

