# scrape

- resource: http://traininfo.jreast.co.jp/train_info/line.aspx?gid=1&lineid=yamanoteline
  scan_interval: 900
  sensor:
    - name: JR info
      select: ".cardsBox"
      value_template: '{{ value.strip() }}'
