# sensors

- platform: integration
  source: sensor.house_power
  name: energy_house
  unit_prefix: k

- platform: statistics
  name: outdoor_stat
  entity_id: sensor.reference
  state_characteristic: average_linear
  sampling_size: 1200
  max_age:
    hours: 24

- platform: filter
  name: outdoor_average
  entity_id: sensor.reference
  filters:
    - filter: time_simple_moving_average
      window_size: "24:00"

#- platform: file
#  name: doorphone_latest
#  file_path: /config/doorphone/latest.json

#- platform: file
#  name: trash_day
#  file_path: /config/text/gomi.txt

#- platform: file
#  name: visit_schedule
#  file_path: /config/text/schedule.txt

#- platform: file
#  name: weather_forecast
#  file_path: /config/text/forecast.txt

#- platform: scrape
#  resource: http://weather.livedoor.com/forecast/rss/area/130010.xml
#  name: weather_forecast
#  select: 'description:nth-of-type(3)'
#  value_template: '{{ value }}'

#- platform: netatmo
#  modules:
#    - House
#    - Outdoor

