# sensors

- platform: integration
  source: sensor.house_power
  name: energy_house
  unit_prefix: k

- platform: statistics
  name: outdoor_stat
  entity_id: sensor.reference
  state_characteristic: average_linear
  sampling_size: 1200
  max_age:
    hours: 24

- platform: filter
  name: outdoor_average
  entity_id: sensor.reference
  filters:
    - filter: time_simple_moving_average
      window_size: "24:00"

- platform: template
  sensors:
    reference:
      value_template: >-
        {{ ((states.sensor.outdoor0.state|float) +
            (states.sensor.outdoor1.state|float)) / 2.0 +
           ((states("sensor.living_humidity")|float) +
            (states("sensor.bedroom_humidity")|float) - 80.0) / 20.0 }}

    outdoor_temperature:
      value_template: "{{ ((states.sensor.outdoor0.state|float)+(states.sensor.outdoor1.state|float))/2.0 }}"

    entrance_temp:
      value_template: "{{ states.sensor.hue_motion_sensor_temperature.state }}"

    entrance_lux:
      value_template: "{{ states.sensor.hue_motion_sensor_light_level.state|float(0)|round(1) }}"

    dishwasher_power:
      value_template: >-
        {{ states('sensor.tasmota_energy_power')|float(0) }}

    drumwasher_power:
      value_template: >-
        {{ states('sensor.tasmotadrum_energy_power')|float(0) }}

- platform: folder
  folder: /config/doorphone

- platform: template
  sensors:
    doorphone_counter:
      value_template: "{{ states.sensor.doorphone.attributes.number_of_files }}"

- platform: file
  name: trash_day
  file_path: /config/text/gomi.txt

- platform: file
  name: visit_schedule
  file_path: /config/text/schedule.txt

- platform: file
  name: weather_forecast
  file_path: /config/text/forecast.txt

#- platform: scrape
#  resource: http://weather.livedoor.com/forecast/rss/area/130010.xml
#  name: weather_forecast
#  select: 'description:nth-of-type(3)'
#  value_template: '{{ value }}'

#- platform: netatmo
#  modules:
#    - House
#    - Outdoor

