# switch

- platform: template
  switches:
    heat_living:
      value_template: >-
        {{   ( is_state('climate.living_aircon', 'heat')
            or is_state('climate.living_aircon', 'auto') )
           and is_state('switch.floor_heater_living', 'on')
           and is_state('switch.floor_heater_kitchen', 'on') }}
      turn_on:
        service: script.turn_on
        entity_id: script.heat_living
      turn_off:
        service: script.turn_on
        entity_id: script.off_living
    heat_bedroom:
      value_template: >-
        {{    is_state('climate.bedroom_aircon', 'heat')
           or is_state('climate.bedroom_aircon', 'auto') }}
      turn_on:
        service: script.turn_on
        entity_id: script.heat_bedroom
      turn_off:
        service: script.turn_on
        entity_id: script.off_bedroom
    cool_living:
      value_template: >-
        {{    is_state('climate.living_aircon', 'cool')
           or is_state('climate.living_aircon', 'auto') }}
      turn_on:
        service: script.turn_on
        entity_id: script.cool_living
      turn_off:
        service: script.turn_on
        entity_id: script.off_living
    cool_bedroom:
      value_template: >-
        {{    is_state('climate.bedroom_aircon', 'cool')
           or is_state('climate.bedroom_aircon', 'auto') }}
      turn_on:
        service: script.turn_on
        entity_id: script.cool_bedroom
      turn_off:
        service: script.turn_on
        entity_id: script.off_bedroom

